# Auto-label PRs based on changed files
"area: core":
  - any: ["Dockerfile", "entrypoit.sh", "patches/**"]

"area: tests":
  - any: ["tests/**"]

"area: docs":
  - any: ["*.md", "docs/**"]

"area: ci/cd":
  - any: [".github/**"]
